"""
src/run_official_spro.py
------------------------
Runs the OFFICIAL MVTec LOCO AD evaluation (sPRO metric & AUROC).
Directly executes MVTec's official evaluate_experiment.py and print_metrics.py.

PREREQUISITES:
  1. Anomaly maps saved in TIFF float32 format:
       python src/benchmark_all.py --save_maps
  2. Dataset and evaluation kit set up via:
       python setup_cloud.py

USAGE:
  python src/run_official_spro.py
"""
import sys, json, subprocess, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.append(str(ROOT))

CATEGORIES = [
    "breakfast_box",
    "juice_bottle",
    "pushpins",
    "screw_bag",
    "splicing_connectors"
]

MODELS = ["gct", "baseline"]
EVAL_DIR    = ROOT / "mvtec_loco_ad_evaluation"
EVAL_SCRIPT = EVAL_DIR / "evaluate_experiment.py"
PRINT_SCRIPT= EVAL_DIR / "print_metrics.py"
DATASET_DIR = (ROOT / "data" / "mvtec_loco") if (ROOT / "data" / "mvtec_loco").exists() else (ROOT / "data" / "mvtec_loco_ad")
MAPS_DIR    = ROOT / "outputs" / "anomaly_maps"
OUTPUT_DIR  = ROOT / "results" / "official_metrics"

def check_prerequisites():
    """Verify that all required files and directories exist before running."""
    errors = []

    if not EVAL_SCRIPT.exists():
        errors.append(
            f"[MISSING] {EVAL_SCRIPT.relative_to(ROOT)}\n"
            "  → Please run: python setup_cloud.py to auto-download the official kit."
        )

    if not DATASET_DIR.exists():
        errors.append(
            f"[MISSING] {DATASET_DIR.relative_to(ROOT)}\n"
            "  → Please run: python setup_cloud.py to auto-download dataset."
        )

    for model in MODELS:
        maps_root = MAPS_DIR / model
        if not maps_root.exists():
            errors.append(
                f"[MISSING] Anomaly maps for '{model}' at: {maps_root.relative_to(ROOT)}\n"
                "  → Run first: python src/benchmark_all.py --save_maps"
            )

    if errors:
        print("\n" + "=" * 70)
        print("❌ PREREQUISITES CHECK FAILED:")
        print("=" * 70)
        for e in errors:
            print(f"\n{e}")
        print("\n" + "=" * 70)
        sys.exit(1)

    print("[OK] All prerequisites found. Starting official MVTec evaluation...")

def run_official_eval_for_category(model: str, category: str):
    """
    Invoke MVTec's evaluate_experiment.py for one model × category.
    """
    maps_dir   = MAPS_DIR / model
    output_dir = OUTPUT_DIR / model / category
    output_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable,
        str(EVAL_SCRIPT),
        "--dataset_base_dir", str(DATASET_DIR),
        "--anomaly_maps_dir", str(maps_dir),
        "--output_dir", str(output_dir),
        "--object_name", category,
    ]

    print(f"\n>>> [OFFICIAL EVAL] Model={model:<8} Category={category:<20}")
    result = subprocess.run(cmd, cwd=str(EVAL_DIR))
    if result.returncode != 0:
        print(f"  [WARN] Non-zero exit code for {model}/{category}")

def print_official_summary_tables():
    """Call MVTec's print_metrics.py to display standard tables."""
    if not PRINT_SCRIPT.exists():
        return

    print("\n" + "=" * 80)
    print("🏆 OFFICIAL MVTEC LOCO AD BENCHMARK TABLES (Generated by print_metrics.py)")
    print("=" * 80)

    # 1. Localization (sPRO @ FPR=0.05 - Standard Protocol)
    print("\n📊 [1/3] Localization: sPRO @ FPR = 0.05 (Standard International Benchmark)")
    subprocess.run([
        sys.executable, str(PRINT_SCRIPT),
        "--metrics_folder", str(OUTPUT_DIR),
        "--metric_type", "localization",
        "--integration_limit", "0.05"
    ], cwd=str(EVAL_DIR))

    # 2. Localization (sPRO @ FPR=0.30)
    print("\n📊 [2/3] Localization: sPRO @ FPR = 0.30")
    subprocess.run([
        sys.executable, str(PRINT_SCRIPT),
        "--metrics_folder", str(OUTPUT_DIR),
        "--metric_type", "localization",
        "--integration_limit", "0.3"
    ], cwd=str(EVAL_DIR))

    # 3. Classification (Image AUROC)
    print("\n📊 [3/3] Classification: Image-level AU-ROC")
    subprocess.run([
        sys.executable, str(PRINT_SCRIPT),
        "--metrics_folder", str(OUTPUT_DIR),
        "--metric_type", "classification"
    ], cwd=str(EVAL_DIR))

def main():
    print("=" * 80)
    print("🚀 RUNNING OFFICIAL MVTEC LOCO AD EVALUATION SUITE")
    print("=" * 80)

    check_prerequisites()

    for model in MODELS:
        print(f"\n{'='*50}")
        print(f"📌 Evaluating Model: {'ViTill-GCT V2' if model == 'gct' else 'Dinomaly Baseline'}")
        print(f"{'='*50}")
        for cat in CATEGORIES:
            run_official_eval_for_category(model, cat)

    # Print official formatted tables
    print_official_summary_tables()
    print(f"\n[OK] Official metrics saved in: {OUTPUT_DIR.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
